### ISSUE TITLE
Drag seems to be unscaled

### ISSUE THREAD

**Issue by pellinor0** [pellinor0/TweakScale#2]
(copied from https://github.com/Biotronic/TweakScale/issues/35 )

>> Build a 1.25m rocket body, and put a KS-25x4 "Mammoth" engine on it, tweakscaled to 1.25m. Sea level thrust should be 1/9 of 3746kN = ~416kN. Fly the rocket, observe it can't accelerate past about 300m/s at low altitudes despite the high thrust. F12 to see a very long red drag line.

>> Replace the scaled mammoth with an LV-T30, observe that with half the thrust it has no trouble accelerating past 1000m/s. F12 to see no substantial drag line from the engine.

>> It seems like the drag model still has the engine being 3.75m diameter, so you're trying to fly a supersonic piston head.

**Comment by n0xiety** [comment]
Oh what a coincidence i actually posted a test in dev thread a couple of days ago using a scaled mamooth against spark. Yup seems like the drag model stays the same. Wouldn't hurt to add the pics here i guess.

![tweakscale drag bug](https://cloud.githubusercontent.com/assets/12836558/8113719/915deb10-1078-11e5-8e20-b0280a184734.jpg)
Identical rockets only engine differs. Right one has stock spark while the left one uses mamooth scaled to have the same twr as spark one. Mamooth actually weighs less when scaled to have the same twr. Seeing how mamooth rocket is lighter common sense suggests it should go faster than spark one.
![tweakscale drag bug 2](https://cloud.githubusercontent.com/assets/12836558/8113733/a9f3e0d0-1078-11e5-8b1e-cb917df1290b.jpg)
After launch spark gets a head start and we can see the mamooth struggling behind.
![tweakscale drag bug 3](https://cloud.githubusercontent.com/assets/12836558/8113736/adb10608-1078-11e5-90e1-6b325e18fe6d.jpg)
Mamooth seems to be struggling with staggering drag at such low speed and can't even accelerate.
![tweakscale drag bug 4](https://cloud.githubusercontent.com/assets/12836558/8113738/b06f08d6-1078-11e5-845a-0a4c92e25345.jpg)
On the other hand we see the spark have virtually no drag at all.
![tweakscale drag bug 5](https://cloud.githubusercontent.com/assets/12836558/8113740/b304be74-1078-11e5-9d26-d308503f6a44.jpg)
Distance between goes bigger and bigger. Ended the test after the spark got even faster and distance between them got up to 22km resulting in mamooth despawning in atmosphere.

**Comment by futrtrubl** [comment]
I believe stock aero is now basing it's drag cube on bulkhead profiles, which I don't think get changed by TS. Even more than that I think KSP caches those drag cubes and doesn't rebuild them during play so even if the bulkhead profiles are modified it still may not work. Even then if you got it to redo the drag cube it may apply that to all instances of that part even if they are different sizes....
I hope one of those assumptions are wrong.

**Comment by pellinor0** [comment]
I don't think bulkhead profiles are used for drag, because they are not linked to attachment nodes. There are parts with multiple different nodes, but the list of profiles only lists each size once. So it looks to me like they are only used for sorting in the editor.

**Comment by futrtrubl** [comment]
Yes, you are right. Drag cubes are calculated from the part geometry. Unfortunately they appear to be built once on start.

**Comment by pellinor0** [comment]
Got some good advice here: 
http://forum.kerbalspaceprogram.com/threads/106975-1-0-2-Procedural-Parts-Parts-the-way-you-want-em-v1-1-1-May-12?p=2022033&viewfull=1#post2022033

**Comment by pellinor0** [comment]
Hopefully fixed by https://github.com/pellinor0/TweakScale/commit/3e80ec81eceede2e1fed2f0eed93a866ff1ddea5 and https://github.com/pellinor0/TweakScale/commit/448fa7168cb9ff73c98b8dfebc67797cc76858e0
