### ISSUE TITLE
Add support for fission reactors

### ISSUE THREAD

**Issue by artyom-y-razinov** [pellinor0/TweakScale#37]
Type of issue: Feature request

Problem: to get to another planet fast I use vast amount of fission reactors (to support tweak scaled ion engines), it increases part count and add lags on high speed physics warp (>=20x). It will be cool if fission reactors can be scaled too.

**Comment by pellinor0** [comment]
There are no stock reactors. So what mod are you talking about?

**Comment by artyom-y-razinov** [comment]
Sorry, I thought they are stock. I think functionality is provided by this mod (don't know how to check it, but I'm 99% sure): http://forum.kerbalspaceprogram.com/index.php?/topic/47786-112-near-future-technologies-may-22-nf-construction-update/

They are also used by other mods (like USI Koloniation).

**Comment by pellinor0** [comment]
The NFT reactors should already be scaleable. If not, something broke (I'll revisit those once NFT updates for KSP1.2). 

I prefer not to mess with USI parts, but the converter module used there is supported. So you can easily write your own custom scaling patches (just look into the TweakScale/patches folder and copy from there).
