### ISSUE TITLE
Add support for two new smart parts

### ISSUE THREAD

**Issue by linuxgurugamer** [pellinor0/TweakScale#40]
Please add the following to the KH_SSE_TweakScale.cfg file:

@PART[km_smart_speed] 
{
    %MODULE[TweakScale]
    {
        type = free
    }
}

@PART[km_prox_sensor] 
{
    %MODULE[TweakScale]
    {
        type = free
    }
}

**Comment by pellinor0** [comment]
Thanks, added to dev version.
