### ISSUE TITLE
Cloned fuel tanks' volume reverting

### ISSUE THREAD

**Issue by m9731526** [pellinor0/TweakScale#51]
![sp161024_164132](https://cloud.githubusercontent.com/assets/1814971/19639870/c5369238-9a0c-11e6-9859-933bef3fc7cd.png)
![sp161024_164112](https://cloud.githubusercontent.com/assets/1814971/19639869/c535ec48-9a0c-11e6-9d9c-5dc44da34acc.png)

![sp161024_170700](https://cloud.githubusercontent.com/assets/1814971/19639876/c8f98330-9a0c-11e6-9865-54345fd3d655.png)
![sp161024_170720](https://cloud.githubusercontent.com/assets/1814971/19639875/c8f90ab8-9a0c-11e6-8762-6e88edffc7f9.png)

Nothing related found in log, only the ones I reported earlier about Hangar.

Since it's related to container, I'm thinking about the Configurable Container mod, I've seen that the author said he had provided support to TweakScale, though.

[output_log.txt](https://github.com/pellinor0/TweakScale/files/547322/output_log.txt)

**Comment by pellinor0** [comment]
Since the interaction is handled on the ConfigurableContainers side, the fix will probably happen there. @allista could you have a look? 

Cloned parts come to life a little differently, and I recently found out that TweakScale needs to redo the positions of attachment node on the first update because the game reverts them. Maybe something similar happens to tanks?

**Comment by m9731526** [comment]
I found that it also happens on loading a craft, while solid fuel and other resources volume correctly loaded, liquid fuel volume will revert to the original value of the fuel tank. (tested on stock X200-16 and X200-32)

KSP.log at the time, seems these lines are related:
> [WRN 10:06:05.451] [Part]: PartModule TankManagerUpdater at ResourceTankS, index 7: index exceeds module count as defined in cfg.
> Looking for TankManagerUpdater in other indices...
> [WRN 10:06:05.452] ...no TankManagerUpdater module found on part definition. Skipping...
> [WRN 10:06:05.452] [Part]: PartModule NodesUpdater at ResourceTankS, index 7: index exceeds module count as defined in cfg.
> Looking for NodesUpdater in other indices...
> [WRN 10:06:05.453] ...no NodesUpdater module found on part definition. Skipping...
> [WRN 10:06:05.454] [Part]: PartModule PropsUpdater at ResourceTankS, index 7: index exceeds module count as defined in cfg.
> Looking for PropsUpdater in other indices...
> [WRN 10:06:05.455] ...no PropsUpdater module found on part definition. Skipping...
> [WRN 10:06:05.455] [Part]: PartModule EmitterUpdater at ResourceTankS, index 7: index exceeds module count as defined in cfg.
> Looking for EmitterUpdater in other indices...
> [WRN 10:06:05.456] ...no EmitterUpdater module found on part definition. Skipping...
> [WRN 10:06:05.457] [Part]: PartModule ResourcesUpdater at ResourceTankS, index 7: index exceeds module count as defined in cfg.
> Looking for ResourcesUpdater in other indices...
> [WRN 10:06:05.458] ...no ResourcesUpdater module found on part definition. Skipping...
> [WRN 10:06:05.458] [Part]: PartModule ModuleSwitchableTank at ResourceTankS, index 7: index exceeds module count as defined in cfg.
> Looking for ModuleSwitchableTank in other indices...
> [WRN 10:06:05.459] ...no ModuleSwitchableTank module found on part definition. Skipping...
> [WRN 10:06:05.466] [Part]: PartModule ModuleSwitchableTank at fuelTank2-2, index 4: index exceeds module count as defined in cfg.
> Looking for ModuleSwitchableTank in other indices...
> [WRN 10:06:05.467] ...no ModuleSwitchableTank module found on part definition. Skipping...
> [WRN 10:06:05.468] [Part]: PartModule ModuleSwitchableTank at fuelTank2-2, index 4: index exceeds module count as defined in cfg.
> Looking for ModuleSwitchableTank in other indices...
> [WRN 10:06:05.469] ...no ModuleSwitchableTank module found on part definition. Skipping...
> [WRN 10:06:05.486] [Part]: PartModule ModuleSwitchableTank at fuelTank1-2, index 4: index exceeds module count as defined in cfg.
> Looking for ModuleSwitchableTank in other indices...
> [WRN 10:06:05.487] ...no ModuleSwitchableTank module found on part definition. Skipping...
> [WRN 10:06:05.488] [Part]: PartModule ModuleSwitchableTank at fuelTank1-2, index 4: index exceeds module count as defined in cfg.
> Looking for ModuleSwitchableTank in other indices...
> [WRN 10:06:05.489] ...no ModuleSwitchableTank module found on part definition. Skipping...

**Comment by allista** [comment]
Sorry for not answering right away.

These warnings are irrelevant; they just mean that part configuration does not have ModuleSwitchableTank defined, which is normal, as this module is added dynamically.

@m9731526, I'm very sorry for this misunderstanding, but you're partly mistaken in thinking that CC already have TS support. The version of CC with this support was not yet published.

This issue can be closed.

**Comment by m9731526** [comment]
I see, thanks!
