### ISSUE TITLE
Procedural Parts interaction issue - tweakscaled engines recess into conical tanks

### ISSUE THREAD

**Issue by Spheniscine** [pellinor0/TweakScale#57]
If you put a Tweakscaled engine (I've only tested with downsizing) below a **Procedural Liquid Tank** that has its shape set to **Cone**, save the vessel, then reload the vessel, the engine recesses into the tank, sometimes disappearing within it completely.

**Comment by pellinor0** [comment]
Same error as https://github.com/pellinor0/TweakScale/issues/26 and https://github.com/Swamp-Ig/ProceduralParts/issues/118, so I'll close it as a duplicate.
