### ISSUE TITLE
Not working on Linux

### ISSUE THREAD

**Issue by grasdaggel** [pellinor0/TweakScale#58]
Playing with the latest version of KSP TweakScale doesn work. I'm using TweakScale 1.2.2.

**Comment by pellinor0** [comment]
The current TweakScale version is 2.3.3, and the mod contains no OS-specific things. So this looks like an installation problem on your side. 

What I would do to debug this is
* have a try with only stock+TweakScale
* have a look at the log
http://forum.kerbalspaceprogram.com/index.php?/topic/83212-how-to-get-support-read-first/

**Comment by pellinor0** [comment]
looks like this is solved => closing

**Comment by grasdaggel** [comment]
Yes was indeed a bug on my side, very weird. Forgot one file. :)
