### ISSUE TITLE
Config Update for the NF Technologies Mod Series 

### ISSUE THREAD

**Issue by mikeloeven** [pellinor0/TweakScale#64]
There was a recent update to all the Near Future Technology mods several items were added or updated and no longer work with tweak scale. The configs for this may need to be updated / missing parts added. A cording to another post in the issues section #63 near future construction has no support currently. 

I am wondering if it might be possible down the road to implement a procedural method of adding default tweak scale configs to unknown parts or a debug UI that allows a unsupported part to be configured in-game

**Comment by mikeloeven** [comment]
Looks like some some dashes were added to the part names for readability for example all the orbital engines went from orbitalengine-## to orbital-engine-##

**Comment by mikeloeven** [comment]
Updated Tweak Scale Configs for NFT 
[NFT_TweakScale.cfg.txt](https://github.com/pellinor0/TweakScale/files/853679/NFT_TweakScale.cfg.txt)

**Comment by pellinor0** [comment]
pull request merged, thanks for your contribution
