### ISSUE TITLE
Config options to only scale structural parts?

### ISSUE THREAD

**Issue by TheToric** [pellinor0/TweakScale#72]
not sold on using tweakscale for engines and such, but would like to be able to use it on structural parts, such as parts that either contain no modules or only moduleanimategeneric or some such. quick google search revealed no patch already out there, so i was wondering about your opinions on this?

**Comment by pellinor0** [comment]
This is probably the simplest way to write it as a set of MM patches. 
https://github.com/pellinor0/TweakScale/blob/master/GameData/TweakScale/Examples.cfg#L20-L24

Each patch would blacklist one module (for example ModuleWheelBase would exclude all wheels and landing legs).
